### ISSUE TITLE
Support Airflow Variable?

### ISSUE THREAD

**Issue by everglory99** [etsy/boundary-layer#15]
Hi, 
Thanks for open sourcing boundary-layer, this is really useful! While I am prototyping some plugins for some other open sourced operators and internal operators, I can't find any support for Variables (https://airflow.apache.org/concepts.html#variables).  Am I missing something? Is there a plan to support Variable? The use case is that we want to maintain one yaml file across different environments. Thanks for the help!

**Comment by mchalek** [comment]
hi @everglory99 !  I'm glad to hear that you have found `boundary-layer` useful.

We do not currently have first-class support for variables, although you can in principle access them using the "verbatim string" approach.  It would require specifying that the DAG import the `Variable` class, and it would also only work right now for operator properties that accept strings (as opposed to integers etc).  For example, your workflow might look something like:

```yaml
name: my-workflow

imports:
  objects:
  - module: airflow.model
    object: Variable

operators:
- name: my-operator
  type: my-operator-type
  properties:
    my_arg: <<Variable.get("variable_name")>>
```

Or alternatively you could access them via the airflow jinja templates, as shown in the link you included, again with the requirement that the operator property be of type `string`.

I hope that one of these approaches will be useful to you now, but please let us know if it is not.  We are gradually assembling a feature wish-list for the next significant version bump, and this would certainly be a viable candidate.  We don't use airflow Variables at Etsy so we're not currently prioritizing it, but we're excited to have external interest in this project, so if you need broader support for variables, we'll factor that into our considerations :)

**Comment by everglory99** [comment]
Thanks so much for your help, I totally miss the "verbatim string" part in your blog. After fixing some typos in your code example, the following works great for me! 
```
name: my-workflow

imports:
  objects:
    - module: airflow.models
      objects: 
        - Variable

operators:
- name: my-operator
  type: my-operator-type
  properties:
    my_arg: <<Variable.get("variable_name")>>
```

`boundary-layer` fits perfectly in some of our use cases. I am excited to see this project grow!
